POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Elon Musk",
    "number": "01-23-45-67"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "test": "This is a wrong one"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "01-23-45-67"
}